name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install LHCI
        run: npm install -g @lhci/cli@0.10.x

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lhci autorun --url=https://JSpiegel4.github.io/NewHavenCabin/ --collect.numberOfRuns=1 --upload.artifact=true

      - name: Upload LHCI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
